services:
  forum-back:
    image: forum-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_HOST=mysql_db
      - RABBITMQ_HOST=amqp://localhost:5672
      - RABBITMQ_NOTIF_QUEUE=notif-queue
      - RABBITMQ_DURABLE=true
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
  
  rabbitmq:
    image: rabbitmq:3.12.14-management
    container_name: rabbitmq-dev
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672  
      - 15672:15672  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  
  
volumes:
  rabbitmq_data: